- tools/cache/debugger.css
- tools/cache/debugger.html
- tools/cache/debugger.js
Test URLs:
- After: https://cache-tool-ui--helix-labs-website--adobe.hlx.live/tools/cache/debugger.html?url=https%3A%2F%2Fblog.adobe.com%2Fen%2Fpublish%2F2024%2F04%2F23%2Fadobe-advances-creative-ideation-with-new-firefly-image-3-model
> Cache tool UI

- tools/cache/debugger.css
- tools/cache/debugger.js
minor fixes
Test URLs:
- Before: https://main--helix-labs-website--adobe.hlx.live/tools/cache/debugger.html?url=https%3A%2F%2Fwww.aem.live%2Fdeveloper%2Ftutorial
- After: https://cache-tool-ui--helix-labs-website--adobe.hlx.live/tools/cache/debugger.html?url=https%3A%2F%2Fwww.aem.live%2Fdeveloper%2Ftutorial
> add forwarded host, avoid mutating const

- tools/cache/debugger.js
Test URLs:
- After: https://new-api--helix-labs-website--adobe.hlx.live/tools/cache/debugger.html?url=https://blog.adobe.com/en/publish/2024/04/23/adobe-advances-creative-ideation-with-new-firefly-image-3-model
> fix: update cache tool api

- .github/pull_request_template.md
- blocks/form/checkbox-checked.svg
- blocks/form/checkbox.svg
- blocks/form/form.css
- blocks/form/form.js
- blocks/svg-doctor/svg-doctor.css
- blocks/svg-doctor/svg-doctor.js
- blocks/svg-doctor/w3color.js
- styles/styles.css
- utils/helpers.js
Test URLs:
- Before: https://main--helix-labs-website--adobe.hlx.live/tools/svg-doctor/
- After: https://svg-doctor--helix-labs-website--adobe.hlx.live/tools/svg-doctor/
> svg doctor and its dependencies

- blocks/svg-doctor/svg-doctor.css
Test URLs:
- Before: https://main--helix-labs-website--adobe.hlx.live/tools/svg-doctor/
- After: https://unify--helix-labs-website--adobe.hlx.live/tools/svg-doctor/
> fix: restore vars for svg doctor

- tools/import/import.js
- tools/import/importservice.js
- tools/import/index.html
Test URLs:
- After: https://import-job-param--helix-labs-website--adobe.hlx.live/tools/import/index.html
Changes:
- add `jobid` as URL param
- list all local jobs
- hide api key
> feat: [Bulk import] Deep linking

- tools/import/import.js
Test URLs:
- After: https://import-add-rum--helix-labs-website--adobe.hlx.live/tools/import/index.html
> added rum call to import

- tools/import/import.js
Test URLs:
- After: https://import-remove-rum--helix-labs-website--adobe.hlx.live/tools/import/index.html
- extra rum not needed in `import.js`
https://github.com/adobe/helix-labs-website/pull/18#pullrequestreview-2254927812
> chore: remove extra rum import

- tools/import/import.css
- tools/import/import.js
- tools/import/importservice.js
- tools/import/index.html
- show some progress (spinner, duration)
- make required fields 'required'
- do not pass 'script' if not provided
- do not query if a key was not provided
Fix #<gh-issue-id>
Test URLs:
- After: https://import-progress--helix-labs-website--adobe.hlx.live/tools/import/index.html
> feat: Import progress

- scripts/dom-helpers.js
- styles/colors.css
- styles/containers.css
- styles/styles.css
- styles/typography.css
- tools/bulk/page-status/index.html
- tools/bulk/page-status/scripts.js
- tools/bulk/page-status/styles.css
Test URLs:
- After: https://feat-bulk-status--helix-labs-website--adobe.hlx.live/tools/bulk/page-status
> Bulk Page Preview/Publish Status

- blocks/cards/cards.css
Test URLs:
- Before: https://main--helix-labs-website--adobe.hlx.live/
- After: https://image-filter--helix-labs-website--adobe.hlx.live/
> Image filter

- tools/bulk/page-status/index.html
Test URLs:
- After: https://bug-page-status--helix-labs-website--adobe.hlx.live/tools/bulk/page-status
> Update Page Status help text.

- tools/import/import.js
When the 'Start' button is clicked, scroll down so that the details table is in view right away.
Test URLs:
- After: https://scroll-down--helix-labs-website--adobe.hlx.live/tools/import/index.html
> feat: Scroll down

- tools/site-admin/index.html
- tools/site-admin/site-admin.css
- tools/site-admin/site-admin.js
https://site-admin--helix-labs-website--adobe.aem.page/tools/site-admin/index.html
> chore: rough site admin interface

- tools/site-admin/site-admin.js
https://site-admin--helix-labs-website--adobe.aem.page/tools/site-admin/index.html
> chore: no empty clones

- tools/import/import.css
- tools/import/import.js
- tools/import/importservice.js
- tools/import/index.html
Fix #39 
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/import/index.html
- After: https://import-formdata--helix-labs-website--adobe.aem.live/tools/import/index.html
> #39 Use multipart form data when starting an import job.

- tools/import/index.html
Fix #41 
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/import/index.html
- After: https://no-scroll--helix-labs-website--adobe.aem.live/tools/import/index.html
> Remove scroll to bottom

- tools/cache/debugger.js
depends on https://github.com/adobe/helix-cache-debug/pull/19
> fix: use actualCDNType from response payload

- tools/cache/debugger.js
Fix #<gh-issue-id>
Test URLs:
- After: https://<branch>--helix-labs-website--adobe.aem.live/
> feat: render stack and effective cache control

- tools/cache/debugger.js
Fix #<gh-issue-id>
Test URLs:
- After: https://<branch>--helix-labs-website--adobe.aem.live/
> Even more tweaks

- blocks/header/header.css
- blocks/header/header.js
Test URLs:
- After: https://ribbon--helix-labs-website--adobe.aem.live/
> feat: experimental ribbon

- tools/admin-edit/admin-edit.css
- tools/admin-edit/admin-edit.js
- tools/admin-edit/index.html
- tools/admin-edit/line-highlight.js
this could be extracted for use beyond just `admin-edit`, but a small test case
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.page/tools/admin-edit/index.html
- After: https://syntax-highlight--helix-labs-website--adobe.aem.page/tools/admin-edit/index.html
> feat: textarea that supports syntax-highlighted code

- tools/cache/debugger.css
- tools/cache/debugger.html
- tools/cache/debugger.js
- purge
- show all info button
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/cache/debugger.html
- After: https://cache-debugger--helix-labs-website--adobe.aem.live/tools/cache/debugger.html
> Cache debugger

- tools/cache/debugger.js
ref: https://github.com/adobe/helix-cache-debug/pull/37
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/cache/debugger.html
- After: https://cache-debugger--helix-labs-website--adobe.aem.live/tools/cache/debugger.html
> fix: cache debug auth

- .gitignore
- tools/image-audit/identity/imageidentity/coloridentity.js
- tools/image-audit/identity/imageidentity/perceptualidentity.js
- tools/image-audit/identity/imageidentity/textidentity.js
- tools/image-audit/index.html
- tools/image-audit/package-lock.json
- tools/image-audit/package.json
- tools/image-audit/scripts.js
Some restructuration and cleanup.
Test: https://asset-fix-dep--helix-labs-website--adobe.aem.page/tools/image-audit/index.html
> chore: cleanup image-audit dependencies

- icons/spectrum-copy.svg
- icons/spectrum-download.svg
- tools/cache/debugger.css
- tools/cache/debugger.js
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/cache/debugger.html
- After: https://cache-debugger--helix-labs-website--adobe.aem.live/tools/cache/debugger.html
> fix: syntax highlighting

- package-lock.json
- tools/import/import.css
- tools/import/import.js
- tools/import/importservice.js
- tools/import/index.html
Fix https://jira.corp.adobe.com/browse/SITES-23397
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/import/index.html
- After: https://stop-import--helix-labs-website--adobe.aem.live/tools/import/index.html
Show a "Stop job" button during an import, that stops the job.
> feat: SITES-23397 Stop a running import job

- tools/image-audit/index.html
- tools/image-audit/scripts.js
This allows persists the form in indexxedb for the different sites, and also it allows import and export of the form.
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/image-audit/index.html
- After: https://qol-sitemap-form-persistence--helix-labs-website--adobe.aem.live/tools/image-audit/index.html
> (Chore) QoL sitemap form persistence

- blocks/analyze/analyze.css
Fix #91 
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/powerscore/
- After: https://powerscore-docs--helix-labs-website--adobe.aem.live/tools/powerscore/
> chore: adding docs link to powerscore tool

- tools/snapshot-admin/index.html
- tools/snapshot-admin/palette.css
- tools/snapshot-admin/palette.html
- tools/snapshot-admin/palette.js
- tools/snapshot-admin/snapshot-admin.css
- tools/snapshot-admin/snapshot-admin.js
- tools/snapshot-admin/snapshot-utils.js
https://snapshot-admin--helix-labs-website--adobe.aem.page/tools/snapshot-admin/index.html
> snapshot admin

- 404.html
- head.html
- tools/admin-edit/index.html
- tools/cache/debugger.html
- tools/deep-psi/deep-psi.html
- tools/image-audit/index.html
- tools/import/index.html
- tools/page-status/index.html
- tools/site-admin/index.html
- tools/snapshot-admin/index.html
Test URLs:
- After: https://cspnonce--helix-labs-website--adobe.aem.live/
- Before: https://main--helix-labs-website--adobe.aem.live/tools/admin-edit/index.html
- After: https://cspnonce--helix-labs-website--adobe.aem.live/tools/admin-edit/index.html
- Before: https://main--helix-labs-website--adobe.aem.live/tools/cache/debugger.html
- After: https://cspnonce--helix-labs-website--adobe.aem.live/tools/cache/debugger.html
- Before: https://main--helix-labs-website--adobe.aem.live/tools/deep-psi/deep-psi.html
- After: https://cspnonce--helix-labs-website--adobe.aem.live/tools/deep-psi/deep-psi.html
- Before: https://main--helix-labs-website--adobe.aem.live/tools/image-audit/index.html
- After: …
> feat: Enable CSP with nonce

- tools/snapshot-admin/palette.css
- tools/snapshot-admin/palette.html
- tools/snapshot-admin/palette.js
- tools/snapshot-admin/snapshot-utils.js
- Before: https://main--helix-labs-website--adobe.aem.live/tools/snapshot-admin/index.html?snapshot=https://main--thinktanked--davidnuescheler.aem.page/.snapshots/default/.manifest.json
- After: https://snapshot-admin--helix-labs-website--adobe.aem.live/tools/snapshot-admin/index.html?snapshot=https://main--thinktanked--davidnuescheler.aem.page/.snapshots/default/.manifest.json
for palette view....
https://main--thinktanked--davidnuescheler.aem.page/pretzels
> [snapshot admin] palette improvements

- tools/user-admin/index.html
- tools/user-admin/user-admin.css
- tools/user-admin/user-admin.js
provide a simple user admin for orgs and site.
Test URLs:
https://user-admin--helix-labs-website--adobe.aem.live/tools/user-admin/index.html
> feat: user admin initial draft (org and site)

- tools/snapshot-admin/palette.css
https://snapshot-scroll--helix-labs-website--adobe.aem.live/tools/snapshot-admin/palette.html
> chore: adjust for scrollbars

- tools/snapshot-admin/401-styles.css
- tools/snapshot-admin/401-test.html
- tools/snapshot-admin/401.js
https://snapshot-review-pw--helix-labs-website--adobe.aem.live/tools/snapshot-admin/401-test.html
dialog to be presented by a `401` on `.reviews` when a review password is set.
> feat: add review password

- tools/user-admin/user-admin.js
https://site-users--helix-labs-website--adobe.aem.live/tools/user-admin/index.html
> fix: works with 404 on site access.json

- tools/snapshot-admin/401.js
https://auth-path--helix-labs-website--adobe.aem.live/tools/snapshot-admin/401-test.html
> chore: add path to reviewpassword cookie

- tools/robots-edit/index.html
- tools/robots-edit/robots-edit.css
- tools/robots-edit/robots-edit.js
https://robots--helix-labs-website--adobe.aem.live/tools/robots-edit/index.html
> robots.txt Editor

- tools/snapshot-admin/palette.css
- tools/snapshot-admin/palette.js
adding location change on "approve" and allow for removal from snapshot directly from the pages list.
https://review-mods--helix-labs-website--adobe.aem.page/tools/snapshot-admin/palette.html?theme=dark&ref=main&repo=thinktanked&owner=davidnuescheler&host=thinktanked.org&reviewHost=main--thinktanked--davidnuescheler.aem.reviews&project=thinktanked&referrer=https%3A%2F%2Fmain--thinktanked--davidnuescheler.aem.page%2Fpretzels
> chore: adding some mods to palette

- scripts/loader.js
- tools/headers-edit/headers-edit.css
- tools/headers-edit/headers-edit.js
- tools/headers-edit/index.html
- tools/robots-edit/robots-edit.js
https://headers-edit--helix-labs-website--adobe.aem.live/tools/headers-edit/index.html
> [headers edit] initial draft

- tools/image-audit/index.html
- tools/image-audit/scripts.js
- tools/image-audit/styles.css
- Before: https://main--helix-labs-website--adobe.aem.live/tools/image-audit/index.html
- After: https://simplify--helix-labs-website--adobe.aem.live/tools/image-audit/index.html
> chore: simplification

- styles/styles.css
- tools/project-admin/index.html
- tools/project-admin/project-admin.css
- tools/project-admin/project-admin.js
- utils/auth.js
- utils/config/config.js
- utils/login.js
- utils/sidekick.js
https://sk-project-mgr--helix-labs-website--adobe.aem.page/tools/project-admin/index.html
> feat: sidekick project management

- utils/config/config.js
Fix #131 
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/page-status/index.html
- After: https://sk-bug--helix-labs-website--adobe.aem.live/tools/page-status/index.html
> fix: if sidekick cannot get projects, tools should still work

- utils/config/config.js
https://fix-sites-lookup--helix-labs-website--adobe.aem.page/tools/site-admin/index.html
> fix: sites lookup broken

- tools/pdp-scanner/index.html
- tools/pdp-scanner/pdp-scanner.css
- tools/pdp-scanner/pdp-scanner.js
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/pdp-scanner/index.html
- After: https://pdp-scanner--helix-labs-website--adobe.aem.live/tools/pdp-scanner/index.html
> PDP scanner, initial PR

- tools/pdp-scanner/pdp-scanner.js
Fix #<gh-issue-id>
Test URLs:
- After: https://pdp-scanner--helix-labs-website--adobe.aem.live/
> chore: warranty

- tools/page-status/orphaned-pages-popover.css
- tools/page-status/orphaned-pages-popover.html
- tools/page-status/orphaned-pages-popover.js
https://orphaned-pages--helix-labs-website--adobe.aem.live/tools/page-status/orphaned-pages-popover.html?theme=dark&ref=main&repo=thinktanked&owner=davidnuescheler
> orphaned pages popover

- 404.html
- head.html
- tools/admin-edit/index.html
- tools/cache/debugger.html
- tools/cdn-setup/index.html
- tools/deep-psi/deep-psi.html
- tools/headers-edit/index.html
- tools/image-audit/index.html
- tools/import/index.html
- tools/page-status/index.html
- tools/pdp-scanner/index.html
- tools/project-admin/index.html
- tools/robots-edit/index.html
- tools/site-admin/index.html
- tools/snapshot-admin/index.html
- tools/user-admin/index.html
Test URLs:
- After: https://move-to-http-header--helix-labs-website--adobe.aem.live/
> fix: Rename "move-as-header" to "move-to-http-header"

- tools/admin-edit/admin-edit.js
Fix #152
Test URLs:
- After: https://admin-edit-yaml-issue--helix-labs-website--adobe.aem.live/
> fix: JSON.parse breaks for YAML content

- tools/snapshot-admin/snapshot-admin.js
- tools/snapshot-admin/snapshot-details.js
- tools/snapshot-admin/utils.js
wrong branch name
adding show/hide to snapshot admin
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/snapshot-admin/index.html
- After: https://admin-edit-fix--helix-labs-website--adobe.aem.live/tools/snapshot-admin/index.html
> fix: add show/hide for the snapshot pw

- tools/snapshot-admin/palette.css
- tools/snapshot-admin/palette.html
- tools/snapshot-admin/palette.js
- tools/snapshot-admin/popover.css
- tools/snapshot-admin/popover.html
- tools/snapshot-admin/popover.js
- tools/snapshot-admin/snapshot-utils.js
Test URLs:
- After: https://snapshotadmin-palette-fix--helix-labs-website--adobe.aem.live/
> moving current palette to popover. bringing back old palette to reduce disruption to customers

- tools/admin-edit/admin-edit.js
- tools/admin-edit/index.html
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/admin-edit/index.html
- After: https://remove-error-hover--helix-labs-website--adobe.aem.live/tools/admin-edit/index.html
> chore: remove hover and add global login

- tools/site-query/index.html
- tools/site-query/scripts.js
Allow searching for media IDs.
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/site-query/index.html
- After: https://img-search--helix-labs-website--adobe.aem.live/tools/site-query/index.html
> feat: media search

- styles/styles.css
header link styling
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/project-admin/index.html
- After: https://fix-header-styles--helix-labs-website--adobe.aem.live/tools/project-admin/index.html
> fix: header styles

- package.json
- tools/deep-psi/deep-psi.js
- tools/index-admin/index-admin.css
- tools/index-admin/index-admin.js
- tools/index-admin/index.html
- tools/pdp-scanner/pdp-scanner.js
Adding a new tool to help with managing index definitions.
Test URLs:
- After: https://indexing--helix-labs-website--adobe.aem.live/tools/index-admin/index.html
> Index Admin Tool

- blocks/cards/cards.js
- blocks/fragment/fragment.js
- blocks/header/header.css
- blocks/header/header.js
- blocks/profile/profile.css
- icons/feedback.svg
moving https://github.com/adobe/helix-tools-website/pull/100 to labs
Test URLs:
https://header-nav--helix-labs-website--adobe.aem.page/tools/index-admin/index.html
> feat: add flyout header nav

- tools/snapshot-admin/snapshot-details.js
- tools/snapshot-admin/snapshot-utils.js
Test URLs:
- Before: https://main--helix-labs-website--adobe.aem.live/tools/snapshot-admin/index.html?
- After: https://publish-scheduler--helix-labs-website--adobe.aem.live/tools/snapshot-admin/index.html?
> add publish scheduler to snapshot admin
